[bastion]
bastion-host-ip ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/labuser.pem ansible_ssh_common_args='-o ForwardAgent=yes'

[private-instances]
private-instance-ip1 ansible_host=private-instance-ip ansible_ssh_common_args='-o ProxyJump=ubuntu@11.0.1.100' ansible_ssh_user=ubuntu
private-instance-ip2 ansible_host=private-instance-ip ansible_ssh_common_args='-o ProxyJump=ubuntu@11.0.2.100' ansible_ssh_user=ubuntu
